I do not know why, but evaluate_model.py fails to run on this. Submit an pr if you have fix.
